config/routes.rb
Rails.application.routes.draw do
  
  root 'journals#index'
  resources :journals, only: [:create, :new, :tickets]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  # adding in the new tickets page
  get 'journals/tickets', to: 'tickets#index'

  resources :journals do
  resources :tickets, only: [:index] # Add this nesting
  end

  # Defines the root path route ("/")
  # root "posts#index"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journal.rb
class Journal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # def hello
  #  render html: "test"
  # end

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

    def index
        @journals = Journal.all
    end

    def new
        @journal = Journal.new()
    end

    def tickets
        @journal = Journal.tickets()
    end
    
    def create
        @journal = Journal.new(journal_params)
        if @journal.save
            redirect_to root_url
        else
            render :new
        end
    end



    private


    def journal_params
        params.require(:journal).permit(:name)
    end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    # This is where your Ruby logic goes
    # For example: @tickets = Ticket.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/index.html.erb
<!doctype html>
<html lang-"en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>


<body class="<%= 'journals-background' if controller_name == 'journals' && action_name == 'index' %>"> 
    <%= yield %>


<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" href="new.html.erb">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Settings</a>
  </li>
</ul>

<div class="container mt-5">
  <h1><strong>Good afternoon, Saima! ⛅️ </strong></h1>
  <h2> Here is your daily summary on project: <strong> HMCTS CIC</strong> </h2>
  <br>

  <div class="row">
    <div class="col-md-4">
      <div class="dashboard-panel">
        <h3><strong>Tickets</strong></h3>
        <hr>
        <p><strong>35</strong> tickets in total </p>
        <a href="http://localhost:3000/journals/tickets" class="btn btn-outline-secondary">View tickets</a>
        
        <br>
        <br>
        <p><strong>3</strong> Tickets in drafts</p>
        <a href="#" class="btn btn-outline-secondary">View drafts</a>
      </div>
    </div>
        </div>

    
    <div class="col-md-4">
      <div class="dashboard-panel">
        <h3><strong>My tasks</strong></h3>
        <hr>
        <p>
            <strong> 8 </strong> Tasks to do
            <a href="http://localhost:3000/journals/new" class="btn btn-primary mb-4"> View all tasks</a>
        </p> 
        <a href="#" class="btn btn-outline-secondary btn-block">View all tasks</a>
      </div>
    </div>
    

     <div class="col-md-4">
    <div class="dashboard-panel">
    <h3><strong>Build a ticket</strong></h3>
    <hr>
    <form action="/dashboard/submit_activity" method="post">
      <input type="hidden" name="user_id" value="Current-Admin-101">
      
       <div class="form-group mb-4">
        <label for="activityDate">Date of creation</label>
        <input type="date" 
               class="form-control" 
               id="activityDate" 
               name="activity_date" 
               value="<%= Date.today.to_s %>"> 
        </div>

        <div class="form-group mb-3">
        <label for="activityPersona">Assign to persona</label>
        <input type="text" 
               class="form-control"
               id="activityPersona"
               name="Persona"
               placeholder="Judge">
      </div>


      <div class="form-group mb-3">
        <label for="activityType">Ticket Status</label>
        <select class="form-control" id="activityType" name="activity_type">
          <option selected>Draft</option>
          <option>Under Review</option>
          <option>Archive</option>
        </select>
      </div>
      
      <div class="form-group mb-3">
        <label for="activityDescription">Description</label>
        <input type="text" 
               class="form-control"
               id="activityDescription"
               name="description"
               placeholder="To mention in stand-up">
      </div>
      
      <button type="submit" class="btn btn-outline-secondary">
      Save to drafts</button>

      <button type="submit" class="btn btn-success">
      Create ticket</button>
      <hr>
    </form>
    
  </div>
</div>

</div>
</div>
   

<div class="container mt-5">
<h1><strong>All Tickets</strong></h1>
<h2>View tickets that are in drafts, under review or archived</h2>
<div>
<hr>
<em>
    <% @journals.each do |journal| %>
        <%= journal.name %>
    <% end %>
    </em>
</div>

</div>
</body>

</html>

app/views/journals/new.html.erb
<!doctype html>
<html lang-"en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>

  <% # Check if the current view is for the 'new' action of the 'journals' controller %>
  <body class="<%= 'new-background' if controller_name == 'journals' && action_name == 'new' %>"> 
    <%= yield %>


<div class="container mt-5">

  <div class="row">
    <div class="col-md-4">
      <div class="dashboard-panel">
<h1><strong>Build a user story</strong></h1>
<h2>Enter persona information</h2>

<br>

<div class="d-flex align-items-center">
    <%= form_with(model: @journal) do |form| %>

 <div>
   <%= form.label :Name %>
   <%= form.text_field :Name %>


   <%= form.label :Role %>
   <%= form.text_field :Role %>

  

<div class="container mt-5">

  <button type="button" 
                class="btn btn-danger" 
                title="Clear Role Field"
                onclick="document.getElementById('journal_role').value = '';">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z"/>
          </svg>
        
    </button>
</div>
</div>

        <br>
        <div> <%= form.submit %> </div>
        <% end %>
        
            </div>
         </div>
    </div>
 </div>
 </div>

<div class="container mt-5">
 <a href="http://localhost:3000/" class="btn btn-primary btn-block mb-4">Back to dashboard</a>
</div>

</body>

app/views/journals/tickets.html.erb
<!doctype html>
<html lang-"en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>


<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active" href="new.html.erb">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Settings</a>
  </li>
</ul>

<div class="container mt-5">
  <h1><strong>All tickets </strong></h1>
  <h2> View tickets in progress, draft and completion <strong> HMCTS CIC</strong> </h2>
  <br>

  <div class="row">
    <div class="col-md-4">
      <div class="dashboard-panel">
        <h3><strong>Tickets</strong></h3>
        <hr>
        <p>You have <strong>35</strong> tickets in total </p>
        <a href="#" class="btn btn-outline-secondary">View tickets</a>
        
        <br>
        <br>
        <p>You have<strong>3</strong> Tickets in drafts</p>
        <a href="#" class="btn btn-outline-secondary">View drafts</a>
      </div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
   <title>BA Dashboard</title>
   <meta name="viewport" content="width=device-width,initial-scale=1">
   <%= csrf_meta_tags %>
   <%= csp_meta_tag %>

   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   <%= javascript_importmap_tags %>
 </head>

 <body>
   <%= render '/shared/navbar' %>
   <%= yield %>
 </body>
</html>

app/views/shared/_navbar.html.erb
<div>

<div>
   <%= link_to "Full list of user stories", root_path %>   
   <div class="navbar-link">
   <%= link_to "Add User Story", new_journal_path %>
   </div>
</div>

</div>